# Generated by Django 5.0.4 on 2024-04-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_email", "0002_card_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card_text_all",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title1", models.CharField(max_length=100)),
                ("description1", models.TextField()),
                ("title2", models.CharField(max_length=100)),
                ("description2", models.TextField()),
                ("title3", models.CharField(max_length=100)),
                ("description3", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Card_text",
        ),
    ]
