# Generated by Django 5.0.4 on 2024-04-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_email", "0003_card_text_all_delete_card_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price1", models.CharField(max_length=100)),
                ("price2", models.CharField(max_length=100)),
                ("price3", models.CharField(max_length=100)),
            ],
        ),
    ]
