# Generated by Django 5.0.1 on 2024-04-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_email", "0004_pricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="Home_head",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
            ],
        ),
    ]
