# Generated by Django 5.0.1 on 2024-04-14 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_email", "0005_home_head"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Home_head",
        ),
    ]
