# Generated by Django 5.0.1 on 2024-04-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_email", "0007_home_head"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo_text", models.CharField(max_length=200)),
                ("cat1_title", models.CharField(max_length=100)),
                ("cat1_text1", models.CharField(max_length=100)),
                ("cat1_text2", models.CharField(max_length=100)),
                ("cat1_text3", models.CharField(max_length=100)),
                ("cat1_text4", models.CharField(max_length=100)),
                ("cat2_title", models.CharField(max_length=100)),
                ("cat2_text1", models.CharField(max_length=100)),
                ("cat2_text3", models.CharField(max_length=100)),
                ("cat2_text4", models.CharField(max_length=100)),
                ("cat2_text5", models.CharField(max_length=100)),
                ("cat3_title", models.CharField(max_length=100)),
                ("cat3_text1", models.CharField(max_length=100)),
                ("cat3_text2", models.CharField(max_length=100)),
                ("cat3_text3", models.CharField(max_length=100)),
                ("cat3_text4", models.CharField(max_length=100)),
                ("cat4_title", models.CharField(max_length=100)),
                ("cat4_text1", models.CharField(max_length=100)),
                ("cat4_text2", models.CharField(max_length=100)),
                ("cat4_text3", models.CharField(max_length=100)),
                ("cat4_text4", models.CharField(max_length=100)),
            ],
        ),
    ]
