# Generated by Django 5.0.1 on 2024-04-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_email", "0008_footer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="logo_text",
            field=models.TextField(),
        ),
    ]
